color0 #092b34
color1 #fd4663
color2 #67dfe4
color3 #5c93d6
color4 #5852e0
color5 #93e8ec
color6 #96bbe9
color7 #f2f3f3
color8 #5f7474
color9 #fd4663
color10 #67dfe4
color11 #5c93d6
color12 #5852e0
color13 #93e8ec
color14 #96bbe9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #092b34
background            #092b34
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #0c3945
active_border_color   #67dfe4
inactive_border_color #0c3945
url_color             #67dfe4

active_tab_foreground   #182425
active_tab_background   #67dfe4
inactive_tab_foreground #afb6b6
inactive_tab_background #0c3945
cursor_trail_color      #afb6b6
